# Generated by Django 3.2 on 2024-01-15 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='about_title',
            field=models.TextField(default='Titulo', max_length=50, verbose_name='Titulo Nosotros'),
            preserve_default=False,
        ),
    ]
